### ISSUE TITLE
Doesnt have any effect

### ISSUE THREAD

**Issue by kiesenverseist** [ThomasHickman/autocomplete-gml#3]
When i installed this, nothing changed. It did show up on the packages list. The syntax highlighting of gml does work as it should (from the pre-requisite the gml-language package). 

By nothing changing It means the autocomplete box doesn't show. But I could just be doing something wrong.

**Comment by ThomasHickman** [comment]
That seems quite strange. Could you see if there are any errors in the Console (View -> Developer -> Toggle Developer Tools -> Console (at the top))?

**Comment by kiesenverseist** [comment]
Thanks for the fast reply I didn't expect it.

As for the errors there are two but I think that they are unrelated, but here they are anyways:
![screenshot of errors](https://cloud.githubusercontent.com/assets/19500569/15570270/92edeae8-2378-11e6-9648-e39730d7a49e.PNG)

If I could also add that I do have your other package installed (the linter for gml) and it doesnt work either (I do have the necessary packages installed). Other packages that i do have installed are the minimap and the activate-power-mode which both work fine.

It also could be worth noting that when i try to uninstall the package (or any other package for that matter) it gives an error saying that the file does not exist. But after restarting it does get removed from the list. (this probably isn't relevant to you).

**Comment by ThomasHickman** [comment]
Were you trying to get autocompletions on GMX files? I've found a bug where the autocompletion doesn't work with GMX files - you can update this package to get the fix.

**Comment by ThomasHickman** [comment]
Also, at the moment the linter does not work for GMX files, it will only work for script file (GML files). This is because scripts inside a GMX file may not be of the correct syntax e.g.

``` gml
for(var i = 0;i<10;i++){
    do_something()
}
```

will be represented in the GMX file as

``` gml
for(var i = 0;i&lt;10;i++){
    do_something()
}
```

which is the escaped XML version of that script, but not correct GML.

**Comment by kiesenverseist** [comment]
Sadly I was editing .gml files but good you found a bug anyways. I'm beginning to think that there may be a problem with the language-gml plugin as some keywords are not highlighted (such as alarm or the various room or view variables as I have so far seen). If i can get anymore information Ill tell you as soon as possible. Ill also try running the package on another computer because there maybe a problem with my installation.

I am opening the gml files into the Atom editor by setting it as an external editor and opening it from within the the game maker IDE (right click on script and select open in external editor).

**Comment by faissaloo** [comment]
I'm also having the issue, except it also happens with .gml files:

```
No GMX project file found for file: /home/faissaloo/Desktop/Zer0Day/Zer0Day.gmx/scripts/add_to_inv.gml
/opt/atom/resources/app.asar/src/text-editor-component.js:1010 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/opt/atom/resources/app.asar/src/text-editor-component.js:1010 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/home/faissaloo/.atom/packages/autocomplete-gml/lib/GMXFileManager.js:105 No GMX project file found for file: /home/faissaloo/Desktop/Zer0Day/Zer0Day.gmx/scripts/del_from_inv.gml
```

It shouldn't even need it to function though right? I should be able to get standard library stuff by default.

**Comment by kiesenverseist** [comment]
I didn't mean to say that i wasn't having the problem with gml files, I was.

So do you @faissaloo think that it was a problem with it accessing some other functions? Maybe we didn't have a certain package installed that he didn't realize he was using, maybe it went out of support?

I did end up talking to the maker of the language-gml program (not about this) about the syntax highlighting (how it didn't highlight a bunch of different variables) because i though that may play a part. He said it wasn't included because it wasn't necessary when he made it.

I did end up reinstalling the atom IDE so there isn't a problem there.

**Comment by faissaloo** [comment]
@kiesenverseist Honestly, I'm not sure, it seems like it could be something caused by a missing dependancy but I already have autocomplete+ and language-gml installed and up to date... Maybe it's depending on an out of date version of one of its dependancies?

**Comment by ThomasHickman** [comment]
I've had a look at my code now and fixed issues where autocompletions would not be shown with no GMX project file found and bugs to do with the recognition of GMX project files. I've pushed this to GitHub and published a minor version. Hopefully, this has fixed this for you?

**Comment by kiesenverseist** [comment]
Just downloading it and there seems to be an error

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\creative\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

TypeError: Cannot read property 'substr' of null
    at C:\Users\creative\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at C:\Users\creative\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\creative\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\creative\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\creative\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\creative\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -0:42 settings-view:open (atom-pane.pane.active)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "gruvbox-plus-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
autocomplete-gml, v0.1.5
gruvbox-plus-syntax, v1.2.1

# Dev
No dev packages
```

That was it it seems. To be clear, I pressed the download button and that came up.

I did try and it still doesn't work. :cry:

**Comment by ThomasHickman** [comment]
It seems like this bug has already been reported for the settings-view package (https://github.com/atom/settings-view/issues/766). For this, it has been recommended that you run `apm update` in your terminal

**Comment by kiesenverseist** [comment]
It started working thank you so much.
